---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quote-backend-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wtistang/quote-backend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quote-backend-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/kabanero/quote-backend:tkn

